schilljs_spacegame_alliance_controller:
    pattern: /alliance
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_overview_controller:
    pattern: /alliance/overview
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_found_controller:
    pattern: /alliance/found
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_manage_controller:
    pattern: /alliance/manage
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_users_controller:
    pattern: /alliance/users
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }

schilljs_spacegame_alliance_forums_controller:
    pattern: /alliance/forums
    defaults: { _controller: schilljs.spacegame.controller.alliance:nyf }
