imports:
    - { resource: buildings.yml }
    - { resource: controller.yml }

services:
    schilljs.spacegame.core:
        class: schilljs\spacegame\core
        arguments:
            - @controller.helper
            - @dbal.conn
            - @user
            - @schilljs.spacegame.user
            - @schilljs.spacegame.queue
            - @schilljs.spacegame.tables

    schilljs.spacegame.navigation:
        class: schilljs\spacegame\navigation
        arguments:
            - @controller.helper
            - @template
            - @user
            - @schilljs.spacegame.user

    schilljs.spacegame.queue:
        class: schilljs\spacegame\queue
        arguments:
            - @dbal.conn

    schilljs.spacegame.tables:
        class: schilljs\spacegame\tables
        arguments:
            - %core.table_prefix%

    schilljs.spacegame.user:
        class: schilljs\spacegame\user
        arguments:
            - @dbal.conn
            - @schilljs.spacegame.tables
