services:
    schilljs.spacegame.controller.statistics:
        class: schilljs\spacegame\controller\statistics
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%space_users
            - %core.table_prefix%space_alliances
